language: cpp

before_install:
    - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
#     - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update

install:
#  - sudo apt-get install software-properties-common
#  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
#  - sudo apt-get update -y -qq
#  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y -qq
  - sudo apt-get install -y -qq lcov cmake curl git subversion gcc-avr avr-libc avrdude build-essential libqtcore4 libqt4-dev qt4-qmake g++ cmake libxerces-c-dev xsdcxx libsdl1.2-dev libusb-1.0-0 libphonon-dev phonon libqtwebkit-dev python-qt4 python-qt4-dev

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../companion/src && cmake --build .