language: cpp

before_install:
    - sudo apt-get remove cmake cmake-data --yes
    - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
#     - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update
#    - sudo apt-get upgrade -y 
    

install:
#  - sudo apt-get install software-properties-common
#  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
#  - sudo apt-get update -y -qq
#  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y -qq
  - sudo apt-get install -y lcov cmake cmake-data
  
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../companion/src && cmake --build .